#!/usr/bin/env python3
"""Bake the scan code into particles.js and index.html.

    python3 tools/build_qr.py

The field draws a QR in the "Scan" section of the home page, and the matrix
it draws is baked here rather than computed in the browser. The URL never
changes at runtime, so a QR encoder in the page would be a library every
visitor downloads to produce the same rows every time — and a new script
origin for a CSP that currently allows exactly two.

Writes two blocks, each between markers, and nothing else:

  assets/js/particles.js   /* qr:begin */ … /* qr:end */   the rows the field draws
  index.html               <!-- qr:begin --> … <!-- qr:end -->   the no-WebGL fallback

The destination is CANONICAL (tools/siteinfo.py) + TARGET below. Change
either and re-run; then `python3 serve.py --stamp`, because particles.js
has changed and every page carries its ?v= token.

Needs segno, which is pure Python with no dependencies of its own:

    python3 -m pip install --user segno

Error correction is Q (25%), not the M a plain code would use. The code is
drawn out of soft round points rather than printed squares, and the extra
recovery is what pays for that. At this URL it is version 4, 33 x 33,
547 dark modules; the field draws each as a 3 x 3 block of points.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from siteinfo import CANONICAL  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = "services.html"
ERROR = "q"
QUIET = 4          # clear modules round the code; QR_QUIET in particles.js


def rows_for(url):
    try:
        import segno
    except ImportError:
        sys.exit("build_qr.py needs segno:  python3 -m pip install --user segno")
    code = segno.make(url, error=ERROR, micro=False, boost_error=False)
    rows = ["".join("#" if c else "." for c in r) for r in code.matrix]
    return code, rows


def js_block(url, rows):
    body = ",\n".join('    "%s"' % r for r in rows)
    return ("/* qr:begin — generated by tools/build_qr.py; edit the URL there */\n"
            '  var QR_URL  = "%s";\n'
            "  var QR_ROWS = [\n%s\n  ];\n"
            "  /* qr:end */") % (url, body)


def svg_block(rows):
    """One path of horizontal runs — a module per unit, the quiet zone as
    the viewBox margin so the ground the CSS paints includes it."""
    n = len(rows)
    side = n + 2 * QUIET
    d = []
    for y, row in enumerate(rows):
        x = 0
        while x < n:
            if row[x] == "#":
                run = x
                while run < n and row[run] == "#":
                    run += 1
                d.append("M%d %dh%dv1h-%dz" % (x + QUIET, y + QUIET, run - x, run - x))
                x = run
            else:
                x += 1
    return ('<!-- qr:begin — generated by tools/build_qr.py -->\n'
            '      <svg class="scan__fallback" viewBox="0 0 %d %d" focusable="false"'
            ' aria-hidden="true" shape-rendering="crispEdges"><path d="%s"/></svg>\n'
            '      <!-- qr:end -->') % (side, side, "".join(d))


def splice(path, pattern, block):
    text = path.read_text()
    new, n = re.subn(pattern, lambda _m: block, text, flags=re.S)
    if n != 1:
        sys.exit("%s: expected one qr:begin/qr:end block, found %d" % (path.name, n))
    if new != text:
        path.write_text(new)
        return True
    return False


def main():
    url = "%s/%s" % (CANONICAL, TARGET)
    code, rows = rows_for(url)
    dark = sum(r.count("#") for r in rows)

    js = splice(ROOT / "assets/js/particles.js",
                r"/\* qr:begin.*?/\* qr:end \*/", js_block(url, rows))
    html = splice(ROOT / "index.html",
                  r"<!-- qr:begin.*?<!-- qr:end -->", svg_block(rows))

    print("  %s" % url)
    print("  version %s-%s, %d x %d, %d dark modules -> %d points"
          % (code.version, code.error.upper(), len(rows), len(rows), dark, dark * 9))
    print("  particles.js %s, index.html %s"
          % ("rewritten" if js else "unchanged", "rewritten" if html else "unchanged"))


if __name__ == "__main__":
    main()
